name: CI / Only building & testing

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make Griadle weapper executable
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: | 
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradlewrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
           echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build (run tests and create fat JAR)
        run: ./gradlew --no-daemon clean build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_X64 || '' }}